feat: check_program_compilation annotations

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -11,7 +11,7 @@ on:
 
 env:
     MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-PAR-2-1-bschocolatine-leticia.fraga.git"
-    EXECUTABLES: "mysh,a.out"
+    EXECUTABLES: "mysh,a.out,notexec"
 
 jobs:
     check_coding_style:
@@ -48,8 +48,13 @@ jobs:
                 for exec in $arrEXEC
                     do
                         echo ${exec}
+                        if [[ ! -f $exec ]]
+                            then
+                                echo "::error title=$exec::Missing $exec"
+                                exit 1
                         if [[ ! -x $exec ]]
                             then
+                                echo "::error title=$exec::$exec is not executable"
                                 exit 1
                         fi
                     done
